'use client'

import { useEffect, useState } from 'react'
import Link from 'next/link'
import { ExternalLink, Loader2, MessageCircle, Minus } from 'lucide-react'
import { InternalChatManager, type InternalChatPayload } from '@/components/internal-chat/internal-chat-manager'

export function InternalChatDock(){
  const [open,setOpen]=useState(false);const [loading,setLoading]=useState(false);const [data,setData]=useState<InternalChatPayload|null>(null);const [unread,setUnread]=useState(0)
  async function openChat(){setOpen(true);setLoading(true);try{const response=await fetch('/api/internal-chat',{cache:'no-store'});if(response.ok)setData(await response.json() as InternalChatPayload)}finally{setLoading(false)}}
  useEffect(()=>{function unreadHandler(event:Event){setUnread((event as CustomEvent<number>).detail)}function openHandler(){openChat()}window.addEventListener('internal-chat-unread',unreadHandler);window.addEventListener('open-internal-chat',openHandler);return()=>{window.removeEventListener('internal-chat-unread',unreadHandler);window.removeEventListener('open-internal-chat',openHandler)}},[])
  return <>{open?<section className="fixed bottom-4 right-4 z-[90] flex h-[min(780px,calc(100vh-32px))] w-[min(1120px,calc(100vw-32px))] flex-col overflow-hidden rounded-[26px] border border-slate-200 bg-white shadow-[0_25px_80px_rgba(8,43,77,.28)]"><header className="flex items-center justify-between bg-[#0d5d8b] px-4 py-3 text-white"><div className="flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-white/15"><MessageCircle size={21}/></span><div><h2 className="font-bold">Chat intern Elmont</h2><p className="text-xs text-blue-100">Comunicare rapidă între colegi</p></div></div><div className="flex items-center gap-1"><Link href="/dashboard/chat-intern" className="flex h-9 w-9 items-center justify-center rounded-xl hover:bg-white/15" title="Deschide pagina completă"><ExternalLink size={17}/></Link><button onClick={()=>setOpen(false)} className="flex h-9 w-9 items-center justify-center rounded-xl hover:bg-white/15" title="Minimizează"><Minus size={19}/></button></div></header><div className="min-h-0 flex-1">{loading&&!data?<div className="flex h-full items-center justify-center text-[#197fb5]"><Loader2 className="animate-spin" size={28}/></div>:data?<InternalChatManager key={data.messages[data.messages.length-1]?.id||'empty'} initialData={data} embedded/>:<div className="flex h-full items-center justify-center text-sm text-slate-500">Chatul nu a putut fi încărcat.</div>}</div></section>:<button onClick={openChat} className="fixed bottom-5 right-5 z-[70] flex items-center gap-3 rounded-full bg-[#0d5d8b] py-2.5 pl-3 pr-5 text-white shadow-[0_14px_35px_rgba(8,43,77,.32)] transition hover:-translate-y-1 hover:bg-[#197fb5]" aria-label="Deschide chatul intern"><span className="relative flex h-12 w-12 items-center justify-center rounded-full bg-white/15"><MessageCircle size={27}/>{unread>0&&<b className="absolute -right-1 -top-1 flex h-6 min-w-6 items-center justify-center rounded-full bg-red-600 px-1 text-xs text-white ring-2 ring-white">{unread>99?'99+':unread}</b>}</span><span className="text-left"><strong className="block text-sm">Chat intern</strong><small className="text-blue-100">Deschide conversațiile</small></span></button>}</>
}