'use client'

import { useMemo, useState } from 'react'
import { Archive, Check, Mail, MessageSquare, Phone, Search, Trash2 } from 'lucide-react'

type Message = { id:string; name:string; email:string|null; phone:string|null; message:string; status:'NEW'|'READ'|'REPLIED'|'ARCHIVED'; internalNote:string|null; createdAt:string }

export function MessagesManager({ initialMessages }: { initialMessages: Message[] }) {
  const [items,setItems]=useState(initialMessages); const [query,setQuery]=useState(''); const [filter,setFilter]=useState<'ALL'|Message['status']>('ALL')
  const visible=useMemo(()=>items.filter(item=>(filter==='ALL'||item.status===filter)&&(!query||[item.name,item.email,item.phone,item.message].some(value=>value?.toLowerCase().includes(query.toLowerCase())))),[items,query,filter])
  async function patch(id:string,data:Partial<Message>){const response=await fetch(`/api/messages/${id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});if(response.ok)setItems(current=>current.map(item=>item.id===id?{...item,...data}:item))}
  async function remove(id:string){if(!confirm('Ștergi definitiv mesajul?'))return;const response=await fetch(`/api/messages/${id}`,{method:'DELETE'});if(response.ok)setItems(current=>current.filter(item=>item.id!==id))}
  return <div><header className="mb-6"><span className="text-xs font-black uppercase tracking-[.16em] text-[#197fb5]">Conversații site</span><h1 className="mt-1 text-3xl font-bold text-[#082b4d]">Mesaje</h1><p className="mt-1 text-sm text-slate-500">Întrebările rapide trimise de vizitatorii site-ului.</p></header>
    <div className="mb-5 flex flex-wrap gap-2"><div className="calendar-search !ml-0"><Search size={15}/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Caută nume, telefon, mesaj…"/></div>{(['ALL','NEW','READ','REPLIED','ARCHIVED'] as const).map(value=><button key={value} className={filter===value?'btn-primary':'btn-secondary'} onClick={()=>setFilter(value)}>{value==='ALL'?'Toate':value==='NEW'?'Noi':value==='READ'?'Citite':value==='REPLIED'?'Rezolvate':'Arhivate'}</button>)}</div>
    <div className="grid gap-3">{visible.map(item=><article key={item.id} className={`card p-5 ${item.status==='NEW'?'border-l-4 border-l-red-500':''}`}><div className="flex items-start justify-between gap-4"><div><div className="flex items-center gap-2"><h2 className="font-bold text-[#082b4d]">{item.name}</h2>{item.status==='NEW'&&<span className="rounded-full bg-red-50 px-2 py-1 text-[10px] font-bold uppercase text-red-600">Nou</span>}</div><p className="mt-1 text-xs text-slate-400">{new Date(item.createdAt).toLocaleString('ro-RO')}</p></div><div className="flex gap-1"><button onClick={()=>patch(item.id,{status:'READ'})} className="round-action text-blue-600" title="Marchează citit"><Check size={16}/></button><button onClick={()=>patch(item.id,{status:'ARCHIVED'})} className="round-action text-slate-500" title="Arhivează"><Archive size={16}/></button><button onClick={()=>remove(item.id)} className="round-action text-rose-500" title="Șterge"><Trash2 size={16}/></button></div></div><p className="mt-4 whitespace-pre-wrap rounded-2xl bg-slate-50 p-4 text-sm leading-6 text-slate-700">{item.message}</p><div className="mt-3 flex flex-wrap gap-2">{item.phone&&<a href={`tel:${item.phone}`} className="btn-secondary inline-flex items-center gap-2"><Phone size={15}/>{item.phone}</a>}{item.email&&<a href={`mailto:${item.email}`} className="btn-secondary inline-flex items-center gap-2"><Mail size={15}/>{item.email}</a>}<button onClick={()=>patch(item.id,{status:'REPLIED'})} className="btn-secondary ml-auto inline-flex items-center gap-2"><MessageSquare size={15}/> Marchează rezolvat</button></div></article>)}{!visible.length&&<div className="card p-12 text-center text-slate-500">Nu există mesaje pentru filtrul selectat.</div>}</div>
  </div>
}
