'use client'

import { useMemo, useState } from 'react'
import { useRouter } from 'next/navigation'
import { Calculator, CheckCircle2, FileUp, Loader2, RefreshCw, TriangleAlert } from 'lucide-react'

type Line = { id:string; workingDays:number; workedDays:number; vacationDays:number; medicalDays:number; workedHours:number; overtimeHours:number; attendanceGross:number; overtimeAmount:number; bonuses:number; medicalAllowance:number; mealTickets:number; grossIncome:number; cas:number; cass:number; incomeTax:number; advancePaid:number; otherDeductions:number; netSalary:number; cam:number; employerCost:number; source:string; employee:{ firstName:string; lastName:string; position:string|null } }
type PaymentType = 'NET_SALARIES'|'CAS'|'CASS'|'INCOME_TAX'|'CAM'|'OTHER_DEDUCTIONS'
type Payment = { id:string; type:PaymentType; method:'BANK'|'CASH'; amount:number; paidAt:string|Date }
type Run = { id:string; status:'DRAFT'|'FINALIZED'; minimumGross:number; casRate:number; cassRate:number; incomeTaxRate:number; camRate:number; lines:Line[]; payments:Payment[] } | null
type Preview = { total:number; existing:number; newEmployees:number; salaryRows:number; invalidRows:number[]; duplicateRows:number[]; conflictRows:number[]; records:Array<{row:number;cnp:string;firstName:string;lastName:string;contractNumber:string;grossSalary:number;match:string|null}> }
type D112Status={ready:boolean;officialVersion:string;blockers:string[]}
const money = (value:number) => value.toLocaleString('ro-RO',{minimumFractionDigits:2,maximumFractionDigits:2})

export function PayrollWorkspace({ initialRun, initialMonth, accountingAccess }:{ initialRun:Run; initialMonth:string; accountingAccess:boolean }) {
  const [run,setRun]=useState(initialRun), [busy,setBusy]=useState(''), [file,setFile]=useState<File|null>(null), [preview,setPreview]=useState<Preview|null>(null), [message,setMessage]=useState('')
  const [paymentDate,setPaymentDate]=useState(new Date().toISOString().slice(0,10)), [paymentMethod,setPaymentMethod]=useState<'BANK'|'CASH'>('BANK')
  const [d112,setD112]=useState<D112Status|null>(null)
  const router=useRouter()
  const totals=useMemo(()=>run?.lines.reduce((sum,line)=>({gross:sum.gross+line.grossIncome,cas:sum.cas+line.cas,cass:sum.cass+line.cass,tax:sum.tax+line.incomeTax,net:sum.net+line.netSalary,cam:sum.cam+line.cam,other:sum.other+line.otherDeductions,cost:sum.cost+line.employerCost}),{gross:0,cas:0,cass:0,tax:0,net:0,cam:0,other:0,cost:0})||{gross:0,cas:0,cass:0,tax:0,net:0,cam:0,other:0,cost:0},[run])
  function selectMonth(value:string){router.push(`/dashboard/salarizare?month=${value}`)}
  async function generate(){setBusy('generate');setMessage('');const response=await fetch('/api/payroll',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({month:initialMonth})});const data=await response.json();setBusy('');if(!response.ok)return setMessage(data.error||'Generarea a eșuat.');setRun(data)}
  async function save(line:Line,field:string,value:string){setBusy(line.id+field);const response=await fetch('/api/payroll',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({lineId:line.id,[field]:Number(value||0)})});const data=await response.json();setBusy('');if(!response.ok)return setMessage(data.error||'Salvarea a eșuat.');setRun(current=>current?{...current,lines:current.lines.map(item=>item.id===line.id?{...item,...data}:item)}:current)}
  async function finalize(){if(!confirm('Finalizezi statul și generezi nota contabilă? După finalizare valorile nu mai pot fi modificate.'))return;setBusy('finalize');const response=await fetch('/api/payroll/finalize',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({month:initialMonth})});const data=await response.json();setBusy('');if(!response.ok)return setMessage(data.error||'Finalizarea a eșuat.');setRun(current=>current?{...current,status:'FINALIZED'}:current);setMessage('Stat finalizat și contabilizat.')}
  async function pay(type:PaymentType){const labels:Record<PaymentType,string>={NET_SALARIES:'salariile nete',CAS:'CAS',CASS:'CASS',INCOME_TAX:'impozitul pe salarii',CAM:'CAM',OTHER_DEDUCTIONS:'reținerile către terți'};if(!confirm(`Înregistrezi plata pentru ${labels[type]} la data ${paymentDate}? Operațiunea va genera articol contabil.`))return;setBusy(`pay-${type}`);setMessage('');const response=await fetch('/api/payroll/payments',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({month:initialMonth,type,method:paymentMethod,paidAt:paymentDate})});const data=await response.json();setBusy('');if(!response.ok)return setMessage(data.error||'Plata nu a putut fi înregistrată.');setRun(data);setMessage(`Plata pentru ${labels[type]} a fost înregistrată și contabilizată.`)}
  async function importSaga(commit=false){if(!file)return setMessage('Selectează fișierul SAGA.');setBusy(commit?'import':'preview');const form=new FormData();form.set('file',file);form.set('month',initialMonth);if(commit)form.set('commit','1');const response=await fetch('/api/payroll/saga-import',{method:'POST',body:form});const data=await response.json();setBusy('');if(!response.ok)return setMessage(data.error||'Importul a eșuat.');if(commit){setPreview(null);setMessage(`Import finalizat: ${data.created} angajați noi, ${data.updated} actualizați.`);router.refresh();await generate()}else setPreview(data)}
  async function checkD112(){setBusy('d112');const response=await fetch(`/api/payroll/d112?month=${initialMonth}&view=1`);const data=await response.json();setBusy('');if(!response.ok)return setMessage(data.error||'Prevalidarea D112 a eșuat.');setD112(data)}
  const editable=run?.status==='DRAFT'
  return <div className="space-y-6">
    <div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-extrabold uppercase tracking-[.16em] text-blue-600">Resurse umane</p><h1 className="text-3xl font-bold text-[#082b4d]">Salarizare</h1><p className="mt-1 text-sm text-slate-500">Pontaj → stat de salarii → contribuții → notă contabilă.</p></div><div className="flex flex-wrap gap-2"><input type="month" className="input-field" value={initialMonth} onChange={e=>selectMonth(e.target.value)}/><a href="/dashboard/pontaje" className="btn-secondary">Verifică pontajul</a><a href="/dashboard/angajati" className="btn-secondary">Dosare angajați</a></div></div>
    {message&&<div className={`rounded-xl border p-3 text-sm font-semibold ${message.includes('finalizat')||message.includes('Import finalizat')?'border-emerald-200 bg-emerald-50 text-emerald-700':'border-amber-200 bg-amber-50 text-amber-800'}`}>{message}</div>}
    <section className="card p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-3"><div className="rounded-xl bg-blue-50 p-3 text-blue-700"><FileUp size={20}/></div><div><h2 className="font-bold text-[#082b4d]">Import SAGA / REGES</h2><p className="text-xs text-slate-500">XLSX, CSV, TXT sau XML; actualizare după CNP, contract ori email.</p></div></div><div className="flex flex-wrap gap-2"><input type="file" accept=".xlsx,.csv,.txt,.xml" onChange={e=>{setFile(e.target.files?.[0]||null);setPreview(null)}} className="text-sm"/><button disabled={!file||!!busy} onClick={()=>importSaga(false)} className="btn-secondary">{busy==='preview'?'Se analizează…':'Previzualizează'}</button></div></div>
      {preview&&<div className="mt-4 rounded-xl border border-slate-200 bg-slate-50 p-4"><div className="flex flex-wrap justify-between gap-3"><div><p className="text-sm"><b>{preview.total}</b> rânduri · <b>{preview.existing}</b> actualizări · <b>{preview.newEmployees}</b> angajați noi · <b>{preview.salaryRows}</b> poziții salariale</p>{preview.invalidRows.length>0&&<p className="mt-1 text-xs font-semibold text-red-600">Rânduri neimportabile (identificator lipsă sau CNP invalid): {preview.invalidRows.join(', ')}</p>}{preview.duplicateRows.length>0&&<p className="mt-1 text-xs font-semibold text-red-600">Identificatori repetați la rândurile: {preview.duplicateRows.join(', ')}</p>}{preview.conflictRows.length>0&&<p className="mt-1 text-xs font-semibold text-red-600">Identificatori care corespund mai multor angajați: {preview.conflictRows.join(', ')}</p>}</div><button onClick={()=>importSaga(true)} disabled={!!busy||preview.invalidRows.length>0||preview.duplicateRows.length>0||preview.conflictRows.length>0} className="btn-primary">{busy==='import'?'Se importă…':'Confirmă importul'}</button></div><div className="mt-3 max-h-44 overflow-auto text-xs"><table className="w-full"><thead><tr><th>Rând</th><th>Salariat</th><th>CNP</th><th>Contract</th><th>Brut bază</th><th>Acțiune</th></tr></thead><tbody>{preview.records.slice(0,30).map(row=>{const hasError=preview.invalidRows.includes(row.row)||preview.duplicateRows.includes(row.row)||preview.conflictRows.includes(row.row);return <tr key={row.row} className={hasError?'bg-red-50':''}><td>{row.row}</td><td>{row.lastName} {row.firstName}</td><td>{row.cnp||'—'}</td><td>{row.contractNumber||'—'}</td><td>{money(row.grossSalary)}</td><td>{hasError?'Corectare necesară':row.match?'Actualizare':'Creare'}</td></tr>})}</tbody></table></div></div>}
    </section>
    {!run?<section className="card p-10 text-center"><Calculator className="mx-auto text-blue-400" size={38}/><h2 className="mt-3 text-xl font-bold">Nu există stat pentru {initialMonth}</h2><p className="mt-2 text-sm text-slate-500">Completează salariile brute și pontajele, apoi generează statul.</p><button onClick={generate} disabled={!!busy} className="btn-primary mt-5 inline-flex items-center gap-2">{busy==='generate'?<Loader2 className="animate-spin" size={16}/>:<Calculator size={16}/>} Generează statul</button></section>:
    <><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-6">{[['Brut',totals.gross],['CAS',totals.cas],['CASS',totals.cass],['Impozit',totals.tax],['Net de plată',totals.net],['Cost angajator',totals.cost]].map(([label,value])=><div className="card p-4" key={String(label)}><p className="text-xs font-bold uppercase text-slate-400">{label}</p><p className="mt-1 text-lg font-extrabold text-[#082b4d]">{money(Number(value))} lei</p></div>)}</div>
      <section className="card overflow-hidden"><div className="flex flex-wrap items-center justify-between gap-3 border-b p-4"><div><h2 className="font-bold">Stat salarii {initialMonth}</h2><p className="text-xs text-slate-500">CAS {run.casRate}% · CASS {run.cassRate}% · impozit {run.incomeTaxRate}% · CAM {run.camRate}% · minim {money(run.minimumGross)} lei</p></div><div className="flex gap-2"><a className="btn-secondary" href={`/api/payroll/export?month=${initialMonth}`}>Export CSV</a>{run.status==='FINALIZED'?<span className="inline-flex items-center gap-2 rounded-full bg-emerald-100 px-3 py-2 text-sm font-bold text-emerald-700"><CheckCircle2 size={16}/> Finalizat și contabilizat</span>:<><button className="btn-secondary inline-flex items-center gap-2" onClick={generate} disabled={!!busy}><RefreshCw size={15}/> Recalculează</button>{accountingAccess?<button className="btn-primary" onClick={finalize} disabled={!!busy}>{busy==='finalize'?'Se finalizează…':'Finalizează și contabilizează'}</button>:<span className="rounded-lg bg-amber-50 px-3 py-2 text-xs font-semibold text-amber-800">Finalizarea contabilă necesită acces Contabilitate</span>}</>}</div></div>
      <div className="overflow-x-auto"><table className="min-w-[1580px] w-full text-xs"><thead><tr><th>Angajat</th><th>Zile lucrate/CO/CM</th><th>Ore/supl.</th><th>Brut pontaj</th><th>Supl. lei</th><th>Prime</th><th>CM lei</th><th>Tichete</th><th>Brut</th><th>CAS</th><th>CASS</th><th>Impozit</th><th>Avans</th><th>Rețineri</th><th>Net</th><th>CAM</th><th>Document</th></tr></thead><tbody>{run.lines.map(line=>{const imported=line.source.startsWith('IMPORTED_SAGA');return <tr key={line.id} className={imported?'bg-cyan-50/50':''}><td><b>{line.employee.lastName.toUpperCase()} {line.employee.firstName}</b><div className="text-slate-400">{line.employee.position||'—'}{imported?' · SAGA':''}</div></td><td>{line.workedDays}/{line.vacationDays}/{line.medicalDays} din {line.workingDays}</td><td>{line.workedHours}/{line.overtimeHours}</td><td>{money(line.attendanceGross)}</td>{['overtimeAmount','bonuses','medicalAllowance','mealTickets'].map(field=><td key={field}><input key={`${line.id}-${field}-${line[field as keyof Line]}`} disabled={!editable} aria-label={`${field} ${line.employee.lastName} ${line.employee.firstName}`} className="w-24 rounded-lg border px-2 py-1 text-right" type="number" min="0" step="0.01" defaultValue={line[field as keyof Line] as number} onBlur={e=>save(line,field,e.target.value)}/></td>)}<td className="font-bold">{money(line.grossIncome)}</td><td>{money(line.cas)}</td><td>{money(line.cass)}</td><td>{money(line.incomeTax)}</td>{['advancePaid','otherDeductions'].map(field=><td key={field}><input key={`${line.id}-${field}-${line[field as keyof Line]}`} disabled={!editable} aria-label={`${field} ${line.employee.lastName} ${line.employee.firstName}`} className="w-24 rounded-lg border px-2 py-1 text-right" type="number" min="0" step="0.01" defaultValue={line[field as keyof Line] as number} onBlur={e=>save(line,field,e.target.value)}/></td>)}<td className="font-extrabold text-emerald-700">{money(line.netSalary)}</td><td>{money(line.cam)}</td><td>{run.status==='FINALIZED'?<a className="font-bold text-blue-700 hover:underline" href={`/api/payroll/payslip?lineId=${line.id}`}>PDF</a>:'—'}</td></tr>})}</tbody></table></div></section>
      {run.status==='FINALIZED'&&accountingAccess&&<section className="card p-5"><div className="flex flex-wrap items-end justify-between gap-4"><div><h2 className="font-bold text-[#082b4d]">Plăți salarii și obligații</h2><p className="mt-1 text-xs text-slate-500">Fiecare plată stinge automat contul de datorie prin 5121 (bancă) sau, pentru net, 5311 (casă).</p></div><div className="flex flex-wrap gap-2"><label className="text-xs font-semibold text-slate-600">Data plății<input type="date" className="input-field mt-1 block" value={paymentDate} onChange={e=>setPaymentDate(e.target.value)}/></label><label className="text-xs font-semibold text-slate-600">Metoda<select className="input-field mt-1 block" value={paymentMethod} onChange={e=>setPaymentMethod(e.target.value as 'BANK'|'CASH')}><option value="BANK">Bancă</option><option value="CASH">Casă (doar net)</option></select></label></div></div><div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{([
        ['NET_SALARIES','Salarii nete',totals.net],['CAS','CAS',totals.cas],['CASS','CASS',totals.cass],['INCOME_TAX','Impozit salarii',totals.tax],['CAM','CAM',totals.cam],['OTHER_DEDUCTIONS','Rețineri terți',totals.other],
      ] as Array<[PaymentType,string,number]>).filter(([, ,amount])=>amount>0).map(([type,label,amount])=>{const paid=run.payments?.find(item=>item.type===type);return <div key={type} className="rounded-xl border border-slate-200 p-4"><div className="flex items-start justify-between gap-3"><div><p className="text-sm font-bold">{label}</p><p className="text-lg font-extrabold text-[#082b4d]">{money(amount)} lei</p></div>{paid?<CheckCircle2 className="text-emerald-600" size={20}/>:null}</div>{paid?<p className="mt-2 text-xs font-semibold text-emerald-700">Achitat {String(paid.paidAt).slice(0,10)} · {paid.method==='BANK'?'bancă':'casă'}</p>:<button className="btn-secondary mt-3 w-full" disabled={!!busy||(paymentMethod==='CASH'&&type!=='NET_SALARIES')} onClick={()=>pay(type)}>{busy===`pay-${type}`?'Se înregistrează…':'Înregistrează plata'}</button>}</div>})}</div></section>}
      {run.status==='FINALIZED'&&accountingAccess&&<section className="card p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><h2 className="font-bold text-[#082b4d]">Pregătire D112</h2><p className="mt-1 text-xs text-slate-500">Prevalidare date și fișă de lucru pentru structura ANAF aplicabilă din 07/2026. Depunerea se face numai după validarea cu Soft J ANAF.</p></div><div className="flex flex-wrap gap-2"><button className="btn-secondary" disabled={!!busy} onClick={checkD112}>{busy==='d112'?'Se verifică…':'Verifică datele D112'}</button><a className="btn-secondary" href={`/api/payroll/d112?month=${initialMonth}`}>Export fișă CSV</a><a className="btn-secondary" href="https://static.anaf.ro/static/10/Anaf/Declaratii_R/112.html" target="_blank" rel="noreferrer">Pagina oficială ANAF</a></div></div>{d112&&<div className={`mt-4 rounded-xl border p-4 text-sm ${d112.ready?'border-emerald-200 bg-emerald-50':'border-amber-200 bg-amber-50'}`}><p className="font-bold">{d112.ready?'Date complete pentru validarea în Soft J.':'D112 este blocată până la corectarea datelor.'} <span className="font-normal">Referință: {d112.officialVersion}</span></p>{d112.blockers.length>0&&<ul className="mt-2 list-disc space-y-1 pl-5">{d112.blockers.map(item=><li key={item}>{item}</li>)}</ul>}</div>}</section>}
      <div className="flex gap-2 rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900"><TriangleAlert className="shrink-0" size={18}/><p>Concediile medicale, scutirile speciale și deducerile personale trebuie validate de contabil înainte de finalizare. Valorile importate din SAGA rămân marcate distinct.</p></div></>}
  </div>
}
