"use client";

import { useCallback, useEffect, useState } from "react";
import { AlertTriangle, CheckCircle2, Plus, RefreshCw, Search, ShieldAlert } from "lucide-react";

type Supplier = { id:number; code:string; name:string; cif:string; regCom:string; countryCode:string; county:string; city:string; address:string; postalCode:string; bankAccount:string; bank:string; phone:string; email:string; vatPayer:number; vatOnCollection:number; inactive:number; dueDays:number; blocked:number; warning:number; affiliated:number; notes:string; analyticAccount:string; outstanding:string; invoiceCount:number };
const empty = { name:"",cif:"",regCom:"",countryCode:"RO",county:"",city:"",address:"",postalCode:"",bankAccount:"",bank:"",phone:"",email:"",vatPayer:0,vatOnCollection:0,inactive:0,dueDays:30,blocked:0,warning:0,affiliated:0,notes:"" };

export default function SuppliersPage() {
  const [items,setItems]=useState<Supplier[]>([]),[form,setForm]=useState(empty),[search,setSearch]=useState("");
  const [show,setShow]=useState(false),[editing,setEditing]=useState<number|null>(null),[loading,setLoading]=useState(false),[notice,setNotice]=useState<{ok:boolean;text:string}|null>(null);
  const load=useCallback(async()=>{const r=await fetch(`/api/accounting/suppliers?q=${encodeURIComponent(search)}`);setItems(await r.json())},[search]);
  useEffect(()=>{void load()},[load]);
  async function lookup(){const cui=form.cif.replace(/\D/g,"");if(cui.length<2)return setNotice({ok:false,text:"Introdu CUI-ul furnizorului."});setLoading(true);setNotice(null);try{const r=await fetch(`/api/accounting/anaf-company?cui=${cui}`),b=await r.json();if(!r.ok)throw new Error(b.error);const c=b.company;setForm(x=>({...x,name:c.name||x.name,cif:c.cif||cui,regCom:c.regCom||x.regCom,address:c.address||x.address,county:c.judet||x.county,city:c.city||x.city,postalCode:c.postalCode||x.postalCode,countryCode:c.countryCode||"RO",phone:c.phone||x.phone,vatPayer:c.vatPayer?1:0,inactive:c.inactive?1:0}));setNotice({ok:!c.inactive,text:c.inactive?"Firma figurează inactivă fiscal.":"Date completate din ANAF. Verifică-le înainte de salvare."})}catch(e){setNotice({ok:false,text:e instanceof Error?e.message:"Căutarea ANAF a eșuat."})}finally{setLoading(false)}}
  async function save(){const r=await fetch(editing?`/api/accounting/suppliers/${editing}`:"/api/accounting/suppliers",{method:editing?"PUT":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)}),b=await r.json().catch(()=>({}));if(!r.ok)return setNotice({ok:false,text:b.error||"Salvarea a eșuat."});setForm(empty);setEditing(null);setShow(false);setNotice(null);await load()}
  function edit(s:Supplier){setForm({name:s.name,cif:s.cif,regCom:s.regCom,countryCode:s.countryCode,county:s.county,city:s.city,address:s.address,postalCode:s.postalCode,bankAccount:s.bankAccount,bank:s.bank,phone:s.phone,email:s.email,vatPayer:s.vatPayer,vatOnCollection:s.vatOnCollection,inactive:s.inactive,dueDays:s.dueDays,blocked:s.blocked,warning:s.warning,affiliated:s.affiliated,notes:s.notes});setEditing(s.id);setNotice(null);setShow(true);window.scrollTo({top:0,behavior:"smooth"})}
  return <div><div className="page-head"><div><div className="eyebrow">Nomenclatoare · Terți</div><h1 className="page-title">Furnizori</h1><p className="page-subtitle">Date fiscale, conturi analitice 401, termene și controlul furnizorilor.</p></div><button className="btn-primary" onClick={()=>{setShow(!show);setEditing(null);setForm(empty);setNotice(null)}}><Plus size={15}/>{show?"Închide":"Furnizor nou"}</button></div>
  {show&&<div className="card mb-6"><div className="grid grid-cols-1 md:grid-cols-2 gap-3"><div className="md:col-span-2"><label className="field-label">Denumire furnizor</label><input className="input" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></div><div><label className="field-label">CUI / cod TVA</label><div className="flex gap-2"><input className="input" value={form.cif} onChange={e=>setForm({...form,cif:e.target.value})} onKeyDown={e=>{if(e.key==="Enter"){e.preventDefault();void lookup()}}}/><button className="btn-secondary shrink-0" onClick={lookup} disabled={loading}>{loading?<RefreshCw className="animate-spin" size={14}/>:<Search size={14}/>}Caută ANAF</button></div></div><div><label className="field-label">Registrul Comerțului</label><input className="input" value={form.regCom} onChange={e=>setForm({...form,regCom:e.target.value})}/></div>
  {notice&&<div className={`md:col-span-2 rounded-xl px-3 py-2 flex gap-2 items-center text-sm font-semibold ${notice.ok?"bg-emerald-50 text-emerald-700":"bg-amber-50 text-amber-800"}`}>{notice.ok?<CheckCircle2 size={16}/>:<AlertTriangle size={16}/>} {notice.text}</div>}
  <div className="md:col-span-2"><label className="field-label">Adresă</label><input className="input" value={form.address} onChange={e=>setForm({...form,address:e.target.value})}/></div><div><label className="field-label">Județ</label><input className="input" value={form.county} onChange={e=>setForm({...form,county:e.target.value})}/></div><div><label className="field-label">Localitate</label><input className="input" value={form.city} onChange={e=>setForm({...form,city:e.target.value})}/></div><div><label className="field-label">Țară</label><input className="input" maxLength={2} value={form.countryCode} onChange={e=>setForm({...form,countryCode:e.target.value.toUpperCase()})}/></div><div><label className="field-label">Cod poștal</label><input className="input" value={form.postalCode} onChange={e=>setForm({...form,postalCode:e.target.value})}/></div><div><label className="field-label">IBAN</label><input className="input" value={form.bankAccount} onChange={e=>setForm({...form,bankAccount:e.target.value})}/></div><div><label className="field-label">Banca</label><input className="input" value={form.bank} onChange={e=>setForm({...form,bank:e.target.value})}/></div><div><label className="field-label">Telefon</label><input className="input" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></div><div><label className="field-label">E-mail</label><input className="input" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></div><div><label className="field-label">Termen implicit de plată (zile)</label><input type="number" className="input" value={form.dueDays} onChange={e=>setForm({...form,dueDays:Number(e.target.value)})}/></div><div><label className="field-label">Observații</label><input className="input" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></div>
  <div className="md:col-span-2 flex flex-wrap gap-4 text-sm">{[["vatPayer","Plătitor TVA"],["vatOnCollection","TVA la încasare"],["affiliated","Persoană afiliată"],["warning","Avertizare"],["blocked","Blocat"],["inactive","Inactiv fiscal"]].map(([key,label])=><label key={key} className="flex items-center gap-2"><input type="checkbox" checked={!!form[key as keyof typeof form]} onChange={e=>setForm({...form,[key]:e.target.checked?1:0})}/>{label}</label>)}</div><div className="md:col-span-2"><button className="btn-primary" onClick={save}>{editing?"Salvează modificările":"Adaugă furnizor"}</button></div></div></div>}
  <div className="card mb-4"><label className="field-label">Caută după denumire, CUI sau cod</label><div className="relative"><Search size={15} className="pointer-events-none absolute left-3 top-1/2 -translate-y-1/2" aria-hidden="true"/><input className="input accounting-search-input" value={search} onChange={e=>setSearch(e.target.value)}/></div></div>
  <div className="card-table"><table><thead><tr><th>Cod / furnizor</th><th>Identificare</th><th>Cont analitic</th><th>Contact</th><th className="text-right">Sold</th><th>Status</th><th></th></tr></thead><tbody>{!items.length&&<tr><td colSpan={7} className="empty-row">Niciun furnizor înregistrat.</td></tr>}{items.map(s=><tr key={s.id}><td><strong>{s.code} · {s.name}</strong><div className="text-xs">{s.city||s.address||"—"}</div></td><td className="num">{s.cif||"—"}<div className="text-xs">{s.regCom}</div></td><td><span className="doc-chip">{s.analyticAccount}</span></td><td>{s.phone||"—"}<div className="text-xs">{s.email}</div></td><td className="text-right num">{Number(s.outstanding).toLocaleString("ro-RO",{minimumFractionDigits:2})} RON</td><td>{s.blocked?<span className="badge badge-canceled"><ShieldAlert size={11}/> blocat</span>:s.warning?<span className="badge badge-draft">atenție</span>:<span className="badge badge-paid">activ</span>}</td><td className="text-right"><button className="link-action" onClick={()=>edit(s)}>editează</button></td></tr>)}</tbody></table></div></div>
}
