'use client'

import { useState } from 'react'
import { useRouter } from 'next/navigation'

type Employee = { id: string; firstName: string; lastName: string }
type Leave = { id: string; type: string; startDate: string; endDate: string; reason: string | null; status: string; employee: Employee }
const typeLabels: Record<string, string> = { VACATION: 'Concediu de odihnă', MEDICAL: 'Concediu medical', PERSONAL: 'Zi liberă', UNPAID: 'Fără plată' }
const statusLabels: Record<string, string> = { PENDING: 'În așteptare', APPROVED: 'Aprobat', REJECTED: 'Respins' }

export function LeaveManager({ employees, requests }: { employees: Employee[]; requests: Leave[] }) {
  const [open, setOpen] = useState(false)
  const router = useRouter()
  async function create(formData: FormData) { const r = await fetch('/api/attendance/leaves', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(Object.fromEntries(formData)) }); if (!r.ok) return alert('Cererea nu a putut fi salvată.'); setOpen(false); router.refresh() }
  async function decide(id: string, status: string) { await fetch(`/api/attendance/leaves/${id}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ status }) }); router.refresh() }
  return <div><div className="flex justify-between items-center gap-4 mb-6"><div><h1 className="text-2xl font-semibold">Concedii</h1><p className="text-sm text-slate-500 mt-1">Cereri și aprobări într-un singur loc.</p></div><button className="btn-primary" onClick={() => setOpen(true)}>Cerere nouă</button></div><div className="grid gap-3">{requests.map(r => <div key={r.id} className="card p-4 flex flex-wrap items-center justify-between gap-4"><div><p className="font-medium">{r.employee.firstName} {r.employee.lastName}</p><p className="text-sm text-slate-500">{typeLabels[r.type]} · {new Date(r.startDate).toLocaleDateString('ro-RO')} – {new Date(r.endDate).toLocaleDateString('ro-RO')}</p>{r.reason && <p className="text-sm mt-1">{r.reason}</p>}</div><div className="flex items-center gap-2"><span className="text-xs rounded-full bg-slate-100 px-3 py-1">{statusLabels[r.status]}</span>{r.status === 'PENDING' && <><button className="text-sm text-emerald-700" onClick={() => decide(r.id, 'APPROVED')}>Aprobă</button><button className="text-sm text-rose-600" onClick={() => decide(r.id, 'REJECTED')}>Respinge</button></>}</div></div>)}</div>{open && <div className="fixed inset-0 z-50 bg-black/40 flex items-center justify-center p-4"><form action={create} className="bg-white rounded-3xl p-6 w-full max-w-lg"><h2 className="text-xl font-semibold mb-5">Cerere de concediu</h2><div className="grid gap-3"><select name="employeeId" className="input-field" required><option value="">Selectează angajatul</option>{employees.map(e => <option key={e.id} value={e.id}>{e.firstName} {e.lastName}</option>)}</select><select name="type" className="input-field"><option value="VACATION">Concediu de odihnă</option><option value="MEDICAL">Concediu medical</option><option value="PERSONAL">Zi liberă</option><option value="UNPAID">Fără plată</option></select><div className="grid grid-cols-2 gap-3"><input name="startDate" type="date" className="input-field" required/><input name="endDate" type="date" className="input-field" required/></div><textarea name="reason" className="input-field min-h-24" placeholder="Observații"/></div><div className="flex justify-end gap-2 mt-5"><button type="button" className="btn-secondary" onClick={() => setOpen(false)}>Renunță</button><button className="btn-primary">Trimite</button></div></form></div>}</div>
}
