'use client'

import { Area, AreaChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'

export function ReportCharts({ daily, presence, departments, days }: { daily: { day: string; hours: number }[]; presence: { name: string; value: number; color: string }[]; departments: { name: string; hours: number }[]; days: number }) {
  const maxDepartmentHours = Math.max(1, ...departments.map((department) => department.hours))
  return <div className="grid gap-4 xl:grid-cols-[1.35fr_.65fr]">
    <section className="card min-h-[360px] p-5 lg:p-6"><div className="mb-5"><h2 className="font-semibold">Evoluția orelor lucrate</h2><p className="text-sm text-slate-500">Totalul echipei în ultimele {days} zile.</p></div><div className="h-[270px]"><ResponsiveContainer width="100%" height="100%"><AreaChart data={daily}><defs><linearGradient id="hours" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor="#197fb5" stopOpacity={0.25}/><stop offset="100%" stopColor="#197fb5" stopOpacity={0}/></linearGradient></defs><CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#e8e8ee"/><XAxis dataKey="day" tickLine={false} axisLine={false} fontSize={11}/><YAxis tickLine={false} axisLine={false} fontSize={11}/><Tooltip/><Area type="monotone" dataKey="hours" stroke="#197fb5" strokeWidth={2.5} fill="url(#hours)"/></AreaChart></ResponsiveContainer></div></section>
    <section className="card p-5 lg:p-6"><div><h2 className="font-semibold">Echipă și departamente</h2><p className="text-sm text-slate-500">Prezența și distribuția orelor într-o singură vedere.</p></div><div className="h-[185px]"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={presence} dataKey="value" nameKey="name" innerRadius={48} outerRadius={70} paddingAngle={2}>{presence.map((point) => <Cell key={point.name} fill={point.color}/>)}</Pie><Tooltip/></PieChart></ResponsiveContainer></div><div className="grid grid-cols-2 gap-2">{presence.map((point) => <div key={point.name} className="flex items-center justify-between text-xs"><span className="flex items-center gap-2 text-slate-500"><i className="h-2 w-2 rounded-full" style={{ background: point.color }}/>{point.name}</span><b>{point.value}</b></div>)}</div><div className="mt-5 border-t border-slate-100 pt-4"><p className="mb-3 text-xs font-black uppercase tracking-[.08em] text-slate-400">Ore pe departament</p><div className="space-y-2.5">{departments.map((department) => <div key={department.name}><div className="mb-1 flex justify-between text-xs"><span className="font-semibold text-slate-600">{department.name}</span><b className="text-[#0d5d8b]">{department.hours}h</b></div><div className="h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-gradient-to-r from-[#197fb5] to-[#49a6d4]" style={{ width: `${Math.max(3, department.hours / maxDepartmentHours * 100)}%` }}/></div></div>)}</div></div></section>
  </div>
}