'use client'

import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'

export function ReportCharts({ daily, presence, departments }: { daily: { day: string; hours: number }[]; presence: { name: string; value: number; color: string }[]; departments: { name: string; hours: number }[] }) {
  return <div className="grid xl:grid-cols-[1.35fr_.65fr] gap-4">
    <section className="card p-5 lg:p-6 min-h-[360px]"><div className="mb-5"><h2 className="font-semibold">Evoluția orelor lucrate</h2><p className="text-sm text-slate-500">Totalul echipei în ultimele 30 de zile.</p></div><div className="h-[270px]"><ResponsiveContainer width="100%" height="100%"><AreaChart data={daily}><defs><linearGradient id="hours" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor="#7c3aed" stopOpacity={0.25}/><stop offset="100%" stopColor="#7c3aed" stopOpacity={0}/></linearGradient></defs><CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#e8e8ee"/><XAxis dataKey="day" tickLine={false} axisLine={false} fontSize={11}/><YAxis tickLine={false} axisLine={false} fontSize={11}/><Tooltip/><Area type="monotone" dataKey="hours" stroke="#7c3aed" strokeWidth={2.5} fill="url(#hours)"/></AreaChart></ResponsiveContainer></div></section>
    <section className="card p-5 lg:p-6 min-h-[360px]"><div><h2 className="font-semibold">Starea echipei</h2><p className="text-sm text-slate-500">Distribuția din perioada selectată.</p></div><div className="h-[220px]"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={presence} dataKey="value" nameKey="name" innerRadius={62} outerRadius={88} paddingAngle={2}>{presence.map(p => <Cell key={p.name} fill={p.color}/>)}</Pie><Tooltip/></PieChart></ResponsiveContainer></div><div className="grid grid-cols-2 gap-2">{presence.map(p => <div key={p.name} className="flex items-center justify-between text-sm"><span className="text-slate-500 flex items-center gap-2"><i className="w-2 h-2 rounded-full" style={{ background: p.color }}/>{p.name}</span><b>{p.value}</b></div>)}</div></section>
    <section className="card p-5 lg:p-6 xl:col-span-2 min-h-[340px]"><div><h2 className="font-semibold">Ore pe departament</h2><p className="text-sm text-slate-500">Unde este concentrat timpul de lucru.</p></div><div className="h-[250px] mt-4"><ResponsiveContainer width="100%" height="100%"><BarChart data={departments}><CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#e8e8ee"/><XAxis dataKey="name" tickLine={false} axisLine={false} fontSize={11}/><YAxis tickLine={false} axisLine={false} fontSize={11}/><Tooltip/><Bar dataKey="hours" fill="#22c55e" radius={[7,7,0,0]}/></BarChart></ResponsiveContainer></div></section>
  </div>
}
