'use client'

import { useMemo, useState } from 'react'
import { CheckCircle2, CircleDollarSign, Clock3, FileCheck2, FileText, Inbox, LayoutGrid, List, Mail, MapPin, Phone, Search, Trash2 } from 'lucide-react'
import type { AtrOcrData, OfferSheetData } from '@/lib/offer-sheet'
import { OfferSheetEditor } from '@/components/offers/offer-sheet-editor'
import { InternalAtrUpload } from '@/components/offers/internal-atr-upload'

type OfferStatus = 'NEW' | 'REVIEWING' | 'QUOTED' | 'ACCEPTED' | 'REJECTED' | 'ARCHIVED'
type Offer = { id:string; name:string; email:string; phone:string; serviceType:string; location:string|null; message:string|null; atrPathname:string|null; atrName:string|null; status:OfferStatus; internalNotes:string|null; estimatedValue:number|null; atrOcrData:AtrOcrData|null; offerData:OfferSheetData|null; offerSentAt:string|null; offerEmailSentAt:string|null; offerWhatsappSentAt:string|null; createdAt:string; updatedAt:string }
const STATUS_LABELS:Record<OfferStatus,string>={NEW:'Nouă',REVIEWING:'În analiză',QUOTED:'Ofertă trimisă',ACCEPTED:'Acceptată',REJECTED:'Respinsă',ARCHIVED:'Arhivată'}
const STATUS_CLASSES:Record<OfferStatus,string>={NEW:'bg-blue-50 text-blue-700',REVIEWING:'bg-amber-50 text-amber-700',QUOTED:'bg-violet-50 text-violet-700',ACCEPTED:'bg-emerald-50 text-emerald-700',REJECTED:'bg-rose-50 text-rose-700',ARCHIVED:'bg-slate-100 text-slate-600'}
const FILTERS:Array<'ALL'|OfferStatus>=['ALL','NEW','REVIEWING','QUOTED','ACCEPTED','REJECTED','ARCHIVED']
const money=new Intl.NumberFormat('ro-RO',{style:'currency',currency:'RON',maximumFractionDigits:0})

export function OffersManager({initialOffers,canManage}:{initialOffers:Offer[];canManage:boolean}){
  const[offers,setOffers]=useState(initialOffers);const[filter,setFilter]=useState<'ALL'|OfferStatus>('ALL');const[query,setQuery]=useState('');const[viewMode,setViewMode]=useState<'grid'|'list'>('grid');const[busyId,setBusyId]=useState<string|null>(null);const[editing,setEditing]=useState<Offer|null>(null)
  const visible=useMemo(()=>offers.filter(o=>(filter==='ALL'||o.status===filter)&&(!query||[o.name,o.email,o.phone,o.serviceType,o.location].some(v=>v?.toLocaleLowerCase('ro-RO').includes(query.toLocaleLowerCase('ro-RO'))))),[offers,filter,query])
  const totalEstimated=offers.filter(o=>!['REJECTED','ARCHIVED'].includes(o.status)).reduce((s,o)=>s+(o.estimatedValue||0),0)
  async function patchOffer(id:string,patch:Partial<Pick<Offer,'status'|'internalNotes'|'estimatedValue'>> & {contractNumber?:string}){setBusyId(id);const response=await fetch(`/api/offers/${id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(patch)});const body=await response.json().catch(()=>({}));setBusyId(null);if(!response.ok)return alert(body.error||'Modificarea nu a putut fi salvată.');if(body.nib)alert('Dosarul a fost aprobat și a primit '+body.nib+'. '+(body.notificationSent?'NIB-ul a fost trimis clientului prin e-mail.':'NIB-ul este disponibil în Branșamente.'));setOffers(current=>current.map(o=>o.id===id?{...o,...patch,updatedAt:new Date().toISOString()}:o))}
  async function changeOfferStatus(offer: Offer, status: OfferStatus) {
    if (status !== 'ACCEPTED' || offer.status === 'ACCEPTED') return patchOffer(offer.id, { status })
    const contractNumber = window.prompt('Introdu Numărul contractului. Acesta va stabili și NIB-ul branșamentului:')?.trim()
    if (!contractNumber) return
    if (!/\d/.test(contractNumber)) return alert('Numărul contractului trebuie să conțină cel puțin o cifră.')
    return patchOffer(offer.id, { status, contractNumber })
  }  async function removeOffer(offer:Offer){if(!confirm(`Ștergi definitiv cererea de la ${offer.name}?`))return;setBusyId(offer.id);const response=await fetch(`/api/offers/${offer.id}`,{method:'DELETE'});setBusyId(null);if(!response.ok)return alert('Cererea nu a putut fi ștearsă.');setOffers(current=>current.filter(o=>o.id!==offer.id))}
  return <div><header className="mb-6 flex flex-wrap items-end justify-between gap-4"><div><span className="text-xs font-black uppercase tracking-[.16em] text-[#197fb5]">Solicitări publice</span><h1 className="mt-1 text-3xl font-bold tracking-tight text-[#082b4d]">Oferte</h1><p className="mt-1 text-sm text-slate-500">Cererile de pe site, fișele A4 și trimiterea către beneficiari.</p></div><span className="rounded-full bg-[#edf7fc] px-4 py-2 text-sm font-bold text-[#0f679b]">{offers.filter(o=>o.status==='NEW').length} cereri noi</span></header>
    <div className="mb-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Stat icon={<Inbox/>} label="Cereri totale" value={offers.length}/><Stat icon={<Clock3/>} label="În analiză" value={offers.filter(o=>o.status==='REVIEWING').length}/><Stat icon={<CheckCircle2/>} label="Acceptate" value={offers.filter(o=>o.status==='ACCEPTED').length}/><Stat icon={<CircleDollarSign/>} label="Valoare estimată" value={money.format(totalEstimated)}/></div>
    <div className="mb-5 flex flex-wrap items-center gap-2"><div className="calendar-search !ml-0"><Search size={15}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Caută client, telefon, lucrare…"/></div>{FILTERS.map(status=><button key={status} onClick={()=>setFilter(status)} className={filter===status?'btn-primary':'btn-secondary'}>{status==='ALL'?'Toate':STATUS_LABELS[status]}</button>)}<div className="ml-auto">{canManage&&<InternalAtrUpload/>}</div><div className="inline-flex rounded-xl border border-slate-200 bg-white p-1 shadow-sm" aria-label="Mod de vizualizare"><button type="button" onClick={()=>setViewMode('grid')} className={`rounded-lg p-2 ${viewMode==='grid'?'bg-[#0d5d8b] text-white':'text-slate-500 hover:bg-slate-50'}`} title="Vizualizare grilă"><LayoutGrid size={17}/></button><button type="button" onClick={()=>setViewMode('list')} className={`rounded-lg p-2 ${viewMode==='list'?'bg-[#0d5d8b] text-white':'text-slate-500 hover:bg-slate-50'}`} title="Vizualizare listă"><List size={17}/></button></div></div>
    <div className={`grid gap-4 ${viewMode==='grid'?'xl:grid-cols-2':'grid-cols-1'}`}>{visible.map(offer=><article key={offer.id} className={`card overflow-hidden ${viewMode==='list'?'xl:grid xl:grid-cols-[minmax(0,1fr)_500px] xl:items-stretch':''}`}> <div className="border-b border-slate-100 p-5 xl:border-b-0"><div className="flex items-start justify-between gap-4"><div><div className="flex flex-wrap items-center gap-2"><h2 className="text-lg font-bold text-[#082b4d]">{offer.name}</h2><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${STATUS_CLASSES[offer.status]}`}>{STATUS_LABELS[offer.status]}</span>{offer.atrOcrData&&<span className="rounded-full bg-[#edf7fc] px-2.5 py-1 text-xs font-bold text-[#0f679b]">ATR citit local</span>}</div><p className="mt-1 text-sm font-semibold text-[#197fb5]">{offer.serviceType}</p><p className="mt-1 text-xs text-slate-400">Primită {new Date(offer.createdAt).toLocaleString('ro-RO',{dateStyle:'medium',timeStyle:'short'})}</p></div>{canManage&&<div className="flex shrink-0 items-center gap-2"><button onClick={()=>setEditing(offer)} className="inline-flex items-center gap-2 rounded-xl bg-[#0d5d8b] px-4 py-2.5 text-sm font-bold text-white shadow-sm hover:bg-[#082b4d]"><FileCheck2 size={17}/>{offer.offerData?'Editează fișa ofertei':'Creează fișa ofertei'}</button><button disabled={busyId===offer.id} onClick={()=>removeOffer(offer)} className="round-action text-rose-500" title="Șterge cererea"><Trash2 size={16}/></button></div>}</div>
      <div className="mt-4 flex flex-wrap gap-2 text-sm"><a href={`tel:${offer.phone}`} className="inline-flex items-center gap-2 rounded-xl bg-slate-50 px-3 py-2 font-semibold text-slate-700"><Phone size={15}/>{offer.phone}</a>{offer.email&&<a href={`mailto:${offer.email}`} className="inline-flex items-center gap-2 rounded-xl bg-slate-50 px-3 py-2 font-semibold text-slate-700"><Mail size={15}/>{offer.email}</a>}{offer.location&&<span className="inline-flex items-center gap-2 rounded-xl bg-slate-50 px-3 py-2 text-slate-600"><MapPin size={15}/>{offer.location}</span>}</div>{offer.message&&<p className={`mt-4 rounded-2xl bg-slate-50 p-4 text-sm leading-6 text-slate-600 ${viewMode==='list'?'xl:hidden':''}`}>{offer.message}</p>}
      <div className="mt-4 flex flex-wrap gap-2">{offer.atrPathname&&<a href={`/api/offers/${offer.id}/atr`} target="_blank" className="inline-flex items-center gap-2 rounded-xl border border-[#8bc8e5] bg-[#f4fbfe] px-4 py-2.5 text-sm font-bold text-[#0f679b]"><FileText size={17}/> Deschide ATR</a>}</div>{offer.offerSentAt&&<p className="mt-3 text-xs font-semibold text-emerald-600">Ofertă trimisă la {new Date(offer.offerSentAt).toLocaleString('ro-RO')}</p>}</div>
      {canManage&&<div className="grid gap-4 bg-slate-50/60 p-5 sm:grid-cols-2"><label className="text-xs font-bold text-slate-500">Stadiul ofertării<select value={offer.status} disabled={busyId===offer.id} onChange={e=>changeOfferStatus(offer,e.target.value as OfferStatus)} className="input-field mt-1.5 w-full bg-white">{Object.entries(STATUS_LABELS).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label className="text-xs font-bold text-slate-500">Valoare estimată (lei)<input type="number" min="0" step="100" defaultValue={offer.estimatedValue??''} onBlur={e=>patchOffer(offer.id,{estimatedValue:e.target.value?Number(e.target.value):null})} className="input-field mt-1.5 w-full bg-white"/></label><label className={`text-xs font-bold text-slate-500 sm:col-span-2 ${viewMode==='list'?'xl:hidden':''}`}>Notițe interne<textarea defaultValue={offer.internalNotes||''} onBlur={e=>patchOffer(offer.id,{internalNotes:e.target.value||null})} className="input-field mt-1.5 min-h-20 w-full resize-y bg-white"/></label></div>}</article>)}{!visible.length&&<div className="card p-12 text-center text-slate-500 xl:col-span-2">Nu există cereri pentru filtrul selectat.</div>}</div>
    {editing&&<OfferSheetEditor offer={editing} onClose={()=>setEditing(null)} onSaved={(data,sent)=>{setOffers(current=>current.map(o=>o.id===editing.id?{...o,offerData:data,status:sent?'QUOTED':o.status,estimatedValue:data.executionNet+data.projectNet+(data.panelIncluded?data.panelNet:0),offerSentAt:sent?new Date().toISOString():o.offerSentAt}:o));setEditing(current=>current?{...current,offerData:data}:current)}}/>}
  </div>
}
function Stat({icon,label,value}:{icon:React.ReactNode;label:string;value:string|number}){return <div className="card flex items-center gap-3 p-4"><span className="flex h-11 w-11 items-center justify-center rounded-xl bg-[#edf7fc] text-[#197fb5]">{icon}</span><div><p className="text-xs text-slate-500">{label}</p><p className="text-xl font-bold text-[#082b4d]">{value}</p></div></div>}