"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { AlertTriangle, BookOpenText, CircleDollarSign, Plus, ReceiptText, Trash2, UsersRound } from "lucide-react";

type Supplier={id:number;name:string;cif:string;analyticAccount:string;dueDays:number;blocked:number;vatOnCollection:number};
type Account={code:string;name:string;allowPosting:number;active:number};
type Purchase={id:number;internalNumber:number;supplierName:string;supplierCif:string;documentType:string;documentNumber:string;issueDate:string;dueDate:string;currency:string;subtotal:string;vatTotal:string;total:string;paidAmount:string;status:string;reverseCharge:number};
type Situation={id:number;code:string;name:string;cif:string;analyticAccount:string;documents:number;total:string;paid:string;outstanding:string;overdue:string};
type Line={description:string;expenseAccount:string;unit:string;quantity:string;unitPrice:string;vatRate:string;deductibilityPercent:string};
const today=new Date().toISOString().slice(0,10),yearStart=`${today.slice(0,4)}-01-01`;
const blankLine=():Line=>({description:"",expenseAccount:"628",unit:"buc",quantity:"1",unitPrice:"",vatRate:"21",deductibilityPercent:"100"});
const money=(n:number|string)=>Number(n||0).toLocaleString("ro-RO",{minimumFractionDigits:2,maximumFractionDigits:2});
function addDays(date:string,days:number){const d=new Date(`${date}T12:00:00`);d.setDate(d.getDate()+days);return d.toISOString().slice(0,10)}

export function PurchasesWorkspace(){
 const [tab,setTab]=useState<"entries"|"journal"|"situation">("entries"),[suppliers,setSuppliers]=useState<Supplier[]>([]),[accounts,setAccounts]=useState<Account[]>([]),[purchases,setPurchases]=useState<Purchase[]>([]),[situation,setSituation]=useState<Situation[]>([]),[showForm,setShowForm]=useState(false),[error,setError]=useState("");
 const [from,setFrom]=useState(yearStart),[to,setTo]=useState(today),[paying,setPaying]=useState<Purchase|null>(null),[payment,setPayment]=useState({date:today,amount:"",method:"BANK",reference:""});
 const [form,setForm]=useState({supplierId:"",documentType:"FACTURA",documentNumber:"",issueDate:today,dueDate:today,currency:"RON",exchangeRate:"1",reverseCharge:false,vatOnCollection:false,notes:"",items:[blankLine()]});
 const load=useCallback(async()=>{const [s,a,p]=await Promise.all([fetch("/api/accounting/suppliers").then(r=>r.json()),fetch("/api/accounting/ledger/accounts").then(r=>r.json()),fetch(`/api/accounting/purchases?from=${from}&to=${to}`).then(r=>r.json())]);setSuppliers(s);setAccounts(a);setPurchases(p)},[from,to]);
 const loadSituation=useCallback(async()=>setSituation(await fetch(`/api/accounting/suppliers/situation?asOf=${to}`).then(r=>r.json())),[to]);
 useEffect(()=>{void load()},[load]); useEffect(()=>{if(tab==="situation")void loadSituation()},[tab,loadSituation]);
 const expenseAccounts=useMemo(()=>accounts.filter(a=>a.active&&a.allowPosting&&/^[23678]/.test(a.code)),[accounts]);
 const totals=useMemo(()=>form.items.reduce((v,l)=>{const net=Number(l.quantity||0)*Number(l.unitPrice||0);return{net:v.net+net,vat:v.vat+net*Number(l.vatRate||0)/100}},{net:0,vat:0}),[form.items]);
 function selectSupplier(id:string){const s=suppliers.find(x=>x.id===Number(id));setForm(f=>({...f,supplierId:id,dueDate:addDays(f.issueDate,s?.dueDays||0),vatOnCollection:!!s?.vatOnCollection}))}
 function line(index:number,patch:Partial<Line>){setForm(f=>({...f,items:f.items.map((x,i)=>i===index?{...x,...patch}:x)}))}
 async function save(){setError("");const r=await fetch("/api/accounting/purchases",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...form,supplierId:Number(form.supplierId),exchangeRate:Number(form.exchangeRate),items:form.items.map(x=>({...x,quantity:Number(x.quantity),unitPrice:Number(x.unitPrice),vatRate:Number(x.vatRate),deductibilityPercent:Number(x.deductibilityPercent)}))})}),b=await r.json().catch(()=>({}));if(!r.ok)return setError(b.error||"Documentul nu a putut fi salvat.");setShowForm(false);setForm({supplierId:"",documentType:"FACTURA",documentNumber:"",issueDate:today,dueDate:today,currency:"RON",exchangeRate:"1",reverseCharge:false,vatOnCollection:false,notes:"",items:[blankLine()]});await load()}
 async function pay(){if(!paying)return;setError("");const r=await fetch(`/api/accounting/purchases/${paying.id}/payment`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...payment,amount:Number(payment.amount)})}),b=await r.json().catch(()=>({}));if(!r.ok)return setError(b.error||"Plata nu a putut fi înregistrată.");setPaying(null);await load();if(tab==="situation")await loadSituation()}
 return <div><div className="page-head"><div><div className="eyebrow">Operații · Furnizori</div><h1 className="page-title">Intrări și furnizori</h1><p className="page-subtitle">Facturi de achiziție, TVA deductibilă, plăți, jurnal și scadențe.</p></div><button className="btn-primary" onClick={()=>setShowForm(!showForm)}><Plus size={15}/>{showForm?"Închide":"Intrare nouă"}</button></div>
 <div className="ledger-tabs mb-5">{[["entries","Intrări",ReceiptText],["journal","Jurnal cumpărări",BookOpenText],["situation","Situație furnizori",UsersRound]].map(([id,label,Icon])=><button key={String(id)} className={tab===id?"active":""} onClick={()=>setTab(id as typeof tab)}>{typeof Icon!=="string"&&<Icon size={15}/>} {String(label)}</button>)}</div>
 {error&&<div className="ref-warning mb-4"><AlertTriangle size={16}/>{error}</div>}
 {showForm&&<div className="card mb-6"><div className="grid grid-cols-1 md:grid-cols-4 gap-3"><div className="md:col-span-2"><label className="field-label">Furnizor</label><select className="input" value={form.supplierId} onChange={e=>selectSupplier(e.target.value)}><option value="">— selectează furnizorul —</option>{suppliers.map(s=><option key={s.id} value={s.id} disabled={!!s.blocked}>{s.name} · {s.cif||s.analyticAccount}{s.blocked?" (BLOCAT)":""}</option>)}</select></div><div><label className="field-label">Tip document</label><select className="input" value={form.documentType} onChange={e=>setForm({...form,documentType:e.target.value})}><option value="FACTURA">Factură</option><option value="BON_FISCAL">Bon fiscal</option><option value="AVIZ">Aviz</option><option value="CHITANTA">Chitanță</option></select></div><div><label className="field-label">Număr document</label><input className="input" value={form.documentNumber} onChange={e=>setForm({...form,documentNumber:e.target.value})}/></div><div><label className="field-label">Data documentului</label><input type="date" className="input" value={form.issueDate} onChange={e=>{const s=suppliers.find(x=>x.id===Number(form.supplierId));setForm({...form,issueDate:e.target.value,dueDate:addDays(e.target.value,s?.dueDays||0)})}}/></div><div><label className="field-label">Scadență</label><input type="date" className="input" value={form.dueDate} onChange={e=>setForm({...form,dueDate:e.target.value})}/></div><div><label className="field-label">Monedă</label><select className="input" value={form.currency} onChange={e=>setForm({...form,currency:e.target.value})}><option>RON</option><option>EUR</option><option>USD</option><option>HUF</option></select></div><div><label className="field-label">Curs</label><input type="number" step="0.000001" className="input" value={form.exchangeRate} onChange={e=>setForm({...form,exchangeRate:e.target.value})}/></div></div>
 <div className="purchase-lines mt-5"><div className="purchase-line purchase-line-head"><span>Descriere</span><span>Cont</span><span>UM</span><span>Cant.</span><span>Preț fără TVA</span><span>TVA %</span><span>Deduct. %</span><span></span></div>{form.items.map((x,i)=><div className="purchase-line" key={i}><input className="input" value={x.description} onChange={e=>line(i,{description:e.target.value})} placeholder="Serviciu / marfă"/><select className="input" value={x.expenseAccount} onChange={e=>line(i,{expenseAccount:e.target.value})}>{expenseAccounts.map(a=><option key={a.code} value={a.code}>{a.code} · {a.name}</option>)}</select><input className="input" value={x.unit} onChange={e=>line(i,{unit:e.target.value})}/><input type="number" step="0.001" className="input" value={x.quantity} onChange={e=>line(i,{quantity:e.target.value})}/><input type="number" step="0.01" className="input" value={x.unitPrice} onChange={e=>line(i,{unitPrice:e.target.value})}/><select className="input" value={x.vatRate} onChange={e=>line(i,{vatRate:e.target.value})}><option value="21">21%</option><option value="11">11%</option><option value="9">9%</option><option value="5">5%</option><option value="0">0%</option></select><input type="number" className="input" value={x.deductibilityPercent} onChange={e=>line(i,{deductibilityPercent:e.target.value})}/><button disabled={form.items.length===1} onClick={()=>setForm({...form,items:form.items.filter((_,j)=>j!==i)})}><Trash2 size={15}/></button></div>)}</div>
 <div className="flex flex-wrap justify-between items-end gap-4 mt-4"><div><button className="btn-secondary" onClick={()=>setForm({...form,items:[...form.items,blankLine()]})}><Plus size={14}/>Poziție</button><div className="flex gap-4 mt-3 text-sm"><label><input type="checkbox" checked={form.reverseCharge} onChange={e=>setForm({...form,reverseCharge:e.target.checked})}/> Taxare inversă</label><label><input type="checkbox" checked={form.vatOnCollection} onChange={e=>setForm({...form,vatOnCollection:e.target.checked})}/> TVA la încasare</label></div></div><div className="text-right"><div className="text-sm">Bază: <b>{money(totals.net)} RON</b> · TVA: <b>{money(totals.vat)} RON</b></div><div className="text-xl font-black mt-1">Total: {money(form.reverseCharge?totals.net:totals.net+totals.vat)} RON</div><button className="btn-primary mt-3" onClick={save}>Înregistrează și contează</button></div></div></div>}
 <div className="card mb-4 flex flex-wrap gap-3 items-end"><label><span className="field-label">De la</span><input type="date" className="input" value={from} onChange={e=>setFrom(e.target.value)}/></label><label><span className="field-label">Până la</span><input type="date" className="input" value={to} onChange={e=>setTo(e.target.value)}/></label></div>
 {(tab==="entries"||tab==="journal")&&<div className="card-table"><table><thead><tr><th>Nr. intern / data</th><th>Furnizor</th><th>Document</th><th className="text-right">Bază</th><th className="text-right">TVA</th><th className="text-right">Total</th><th>Scadență / status</th><th></th></tr></thead><tbody>{!purchases.length&&<tr><td colSpan={8} className="empty-row">Nu există intrări în interval.</td></tr>}{purchases.map(p=><tr key={p.id}><td className="num">{p.internalNumber}/{String(p.issueDate).slice(0,4)}<div className="text-xs">{String(p.issueDate).slice(0,10)}</div></td><td><strong>{p.supplierName}</strong><div className="text-xs num">{p.supplierCif}</div></td><td><span className="doc-chip">{p.documentType}</span> {p.documentNumber}{p.reverseCharge?<div className="text-xs">taxare inversă</div>:null}</td><td className="text-right num">{money(p.subtotal)}</td><td className="text-right num">{money(p.vatTotal)}</td><td className="text-right num"><strong>{money(p.total)} {p.currency}</strong><div className="text-xs">plătit {money(p.paidAmount)}</div></td><td>{String(p.dueDate).slice(0,10)}<div><span className={`badge ${p.status==="PAID"?"badge-paid":"badge-draft"}`}>{p.status}</span></div></td><td className="text-right">{p.status!=="PAID"&&<button className="link-action" onClick={()=>{setPaying(p);setPayment({date:today,amount:String(Number(p.total)-Number(p.paidAmount)),method:"BANK",reference:""})}}>plătește</button>}</td></tr>)}</tbody></table></div>}
 {tab==="situation"&&<div className="card-table"><table><thead><tr><th>Furnizor</th><th>Cont</th><th className="text-right">Documente</th><th className="text-right">Total</th><th className="text-right">Plătit</th><th className="text-right">Sold</th><th className="text-right">Restant</th></tr></thead><tbody>{situation.map(s=><tr key={s.id}><td><strong>{s.code} · {s.name}</strong><div className="text-xs num">{s.cif}</div></td><td><span className="doc-chip">{s.analyticAccount}</span></td><td className="text-right">{s.documents}</td><td className="text-right num">{money(s.total)}</td><td className="text-right num">{money(s.paid)}</td><td className="text-right num"><strong>{money(s.outstanding)}</strong></td><td className="text-right num" style={{color:Number(s.overdue)>0?"var(--danger)":undefined}}>{money(s.overdue)}</td></tr>)}</tbody></table></div>}
 {paying&&<div className="modal-backdrop"><div className="card modal-card"><div className="flex justify-between"><div><div className="eyebrow">Plată furnizor</div><h2 className="text-xl font-black">{paying.supplierName}</h2><p className="page-subtitle">Document {paying.documentNumber}</p></div><CircleDollarSign size={26}/></div><div className="grid grid-cols-2 gap-3 mt-5"><div><label className="field-label">Data</label><input type="date" className="input" value={payment.date} onChange={e=>setPayment({...payment,date:e.target.value})}/></div><div><label className="field-label">Sumă</label><input type="number" step="0.01" className="input" value={payment.amount} onChange={e=>setPayment({...payment,amount:e.target.value})}/></div><div><label className="field-label">Metodă</label><select className="input" value={payment.method} onChange={e=>setPayment({...payment,method:e.target.value})}><option value="BANK">Bancă</option><option value="CASH">Numerar</option></select></div><div><label className="field-label">Referință OP/chitanță</label><input className="input" value={payment.reference} onChange={e=>setPayment({...payment,reference:e.target.value})}/></div></div><div className="flex justify-end gap-2 mt-5"><button className="btn-secondary" onClick={()=>setPaying(null)}>Renunță</button><button className="btn-primary" onClick={pay}>Înregistrează plata</button></div></div></div>}
 </div>
}
