"use client";
import { useCallback,useEffect,useState } from "react";
import { Landmark,WalletCards } from "lucide-react";
import { bucharestDate } from "@/lib/accounting/date";
type Register={type:"CASH"|"BANK";accountCode:string;accountName:string;accounts:{code:string;name:string}[];openingBalance:number;totalDebit:number;totalCredit:number;closingBalance:number;entries:Array<{id:number;date:string;entryNumber:number;description:string;documentNumber:string;sourceType:string;debit:number;credit:number;balance:number}>};
const money=(n:number)=>n.toLocaleString("ro-RO",{minimumFractionDigits:2,maximumFractionDigits:2});
export default function RegistersPage(){
 const today=bucharestDate(),[type,setType]=useState<"CASH"|"BANK">("CASH"),[from,setFrom]=useState(`${today.slice(0,7)}-01`),[to,setTo]=useState(today),[account,setAccount]=useState(""),[data,setData]=useState<Register|null>(null),[error,setError]=useState("");
 const load=useCallback(async()=>{setError("");const q=new URLSearchParams({type,from,to,...(account?{account}:{})}),r=await fetch(`/api/accounting/registers?${q}`),b=await r.json();if(!r.ok){setError(b.error||"Registrul nu a putut fi încărcat.");return}setData(b);if(!account)setAccount(b.accountCode)},[type,from,to,account]);
 useEffect(()=>{void load()},[load]);
 function changeType(next:"CASH"|"BANK"){setType(next);setAccount("");setData(null)}
 return <div><div className="page-head"><div><div className="eyebrow">Trezorerie · partidă dublă</div><h1 className="page-title">Registre de casă și bancă</h1><p className="page-subtitle">Încasările și plățile din facturare sunt preluate automat din jurnalul contabil.</p></div></div>
 <div className="ledger-tabs mb-5"><button className={type==="CASH"?"active":""} onClick={()=>changeType("CASH")}><WalletCards size={15}/> Registru de casă</button><button className={type==="BANK"?"active":""} onClick={()=>changeType("BANK")}><Landmark size={15}/> Registru de bancă</button></div>
 <div className="card mb-4 flex flex-wrap gap-3 items-end"><label><span className="field-label">De la</span><input type="date" className="input" value={from} onChange={e=>setFrom(e.target.value)}/></label><label><span className="field-label">Până la</span><input type="date" className="input" value={to} onChange={e=>setTo(e.target.value)}/></label><label><span className="field-label">Cont</span><select className="input" value={account} onChange={e=>setAccount(e.target.value)}>{data?.accounts.map(a=><option key={a.code} value={a.code}>{a.code} · {a.name}</option>)}</select></label></div>
 {error&&<div className="ref-error">{error}</div>}{data&&<><div className="ref-summary-grid">{[["Sold inițial",data.openingBalance],["Încasări / debit",data.totalDebit],["Plăți / credit",data.totalCredit],["Sold final",data.closingBalance]].map(([label,value])=><div className="stat-card" key={String(label)}><div className="stat-label">{label}</div><div className="stat-value">{money(Number(value))} RON</div></div>)}</div>
 <div className="card-table"><table><thead><tr><th>Data</th><th>Nr. notă</th><th>Document</th><th>Explicație</th><th className="text-right">Încasări</th><th className="text-right">Plăți</th><th className="text-right">Sold</th></tr></thead><tbody>{!data.entries.length&&<tr><td colSpan={7} className="empty-row">Nu există operațiuni în interval.</td></tr>}{data.entries.map((row,index)=><tr key={`${row.id}-${index}`}><td className="num">{row.date}</td><td className="num">{row.entryNumber}</td><td><span className="doc-chip">{row.documentNumber||row.sourceType}</span></td><td>{row.description}</td><td className="text-right num">{row.debit?money(row.debit):"—"}</td><td className="text-right num">{row.credit?money(row.credit):"—"}</td><td className="text-right num"><strong>{money(row.balance)}</strong></td></tr>)}</tbody></table></div></>}
 </div>
}
