ALTER TABLE "QuoteRequest" ADD COLUMN IF NOT EXISTS "atrOcrData" JSONB;
ALTER TABLE "QuoteRequest" ADD COLUMN IF NOT EXISTS "offerData" JSONB;
ALTER TABLE "QuoteRequest" ADD COLUMN IF NOT EXISTS "offerSentAt" TIMESTAMP(3);
ALTER TABLE "QuoteRequest" ADD COLUMN IF NOT EXISTS "offerEmailSentAt" TIMESTAMP(3);
ALTER TABLE "QuoteRequest" ADD COLUMN IF NOT EXISTS "offerWhatsappSentAt" TIMESTAMP(3);
